tasks:
  - init: |
      npm install
    command: |
      echo "PUBLIC_URL=$(gp url 3000)" > .env.development.local
      echo "REACT_APP_VERSION=\$npm_package_version" >> .env.development.local
      cp .env.development.local .env.production.local
      npm start
