name: Deploy Site

on:
  release:
    types: [published]

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Identify Commit Hash
        id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - name: Identify version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: change version in NPM
        uses: reedyuk/npm-version@1.1.1
        with:
          version: ${{ steps.get_version.outputs.version-without-v  }}-${{ steps.commit.outputs.short }}
          git-tag-version: 'false'

      - name: 🏗 Build Site
        run: npm ci && npm run build

      - name: 🚛 Publish Site
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: pressify
          directory: ./dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
